#!/bin/sh
#nohup python3 -m http.server --cgi -b 192.227.241.244 -d $HOME/www 14344 &
#nohup python3 -m http.server --cgi -b 127.0.0.1 -d . 14344 &
nohup lighttpd -D -f $HOME/projects/lighttpd.conf &


